### DISCUSSION TITLE
MTU size ?

### DISCUSSION THREAD

**Discussion by haribhusal2025** [spidernet-io/spiderpool#4402] [General]
Generally multus allows defining 'mtu size' for an additional interface. I couldn't find anywhere in spiderpool to define it. For example, if my cluster's primary cluster network is handled by Cilium and i want to use macvlan as an adiitional interface with custom mtu size on it, how or where do i define it ? Please suggest.

**Comment by cyclinder** [comment]
I just tested it and the macvlan subinterface supports configuring mtu, I want to know why you need to configure mtu?

```
ip link add macvlan0 link ens6f1np1 type macvlan mode bridge
ip a show macvlan0
219: macvlan0@ens6f1np1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ***************** brd *****************
ip l set macvlan0 up
ip l set macvlan0 mtu 1480
ip a show macvlan0
219: macvlan0@ens6f1np1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc noqueue state UP group default qlen 1000
    link/ether ***************** brd *****************
    inet6 **********:24ff:fe4f:e5d0/64 scope link 
       valid_lft forever preferred_lft forever
```

**Reply by haribhusal2025** [reply]
Hi, what i meant is: 
How below config in multus allows us to attach a network to a pod with custom mtu configuration, why it is not possible in spiderpool ?
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth1",
            "mode": "bridge",
            "mtu": "1480",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.10.0.0/16",
                         "rangeStart": "10.10.1.20",
                         "rangeEnd": "10.10.3.50",
                         "gateway": "10.10.0.254"
                    } ]
                ]
            }
        }'
EOF
```

Here, it doesnt allow me to define mtu:
```
MACVLAN_MASTER_INTERFACE="ens192"
MACVLAN_MULTUS_NAME="macvlan-$MACVLAN_MASTER_INTERFACE"

cat <<EOF | kubectl apply -f -
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: ${MACVLAN_MULTUS_NAME}
  namespace: kube-system
spec:
  cniType: macvlan
  enableCoordinator: true
  macvlan:
    master:
    - ${MACVLAN_MASTER_INTERFACE}
  mtu: 1400 // or "1400"
EOF
```
