### ISSUE TITLE
跨节点Pod之间网络不通 

### ISSUE THREAD

**Issue by pengbinbin1** [spidernet-io/spiderpool#1328]
**Describe the version**
version about:
1. spiderpool 0.3.6
2. kubernetes  1.20
3. what CNI and itsversion  SR-IOV

**Describe the bug**
试了一下Node Affinity的功能，其中Node1指定网段178.18.41.0/24  Nod2指定网段178.18.42.0/24  创建两个Pod调度到两个节点 两个Pod的IP安照网段被分配出来  但是登录其中之一的Pod内部 Ping另外的Pod 网络不通。

**Hwo To Reproduce**
Steps to reproduce the issue:

**Expected behavior**

**Screenshots and log**
If applicable, add screenshots and log to help explain your problem.

**Additional context**

**Comment by weizhoublue** [comment]
IPAM 层面 只 分配IP，由 CNI 分配到网卡

具体连通性，由 CNI 保证，或者 underlay 网络、路由器本身 决定，只要IPAM分出出 符合意愿的IP和路由，其它的连通性问题非IPAM产生

一些建议
（1）cni 是什么选项，是否工作正常，使得 pod 流量能够出 宿主机，与 同子网 其它ip 通信，例如可以先测试 pod 到 自己子网网关的连通性
（2）给出的描述中，是2个跨子网的网段，2个网段的 路由器 是否 子网打通
（3）画出 拓扑图，逐跳 确认  ( pod  178.18.41.0/24)   to (  178.18.41.0/24 网关 ) to (178.18.42.0/24 网关) to   ( pod  178.18.42.0/24)  的连通性

**Comment by pengbinbin1** [comment]
> IPAM 层面 只 分配IP，由 CNI 分配到网卡
> 
> 具体连通性，由 CNI 保证，或者 underlay 网络、路由器本身 决定，只要IPAM分出出 符合意愿的IP和路由，其它的连通性问题非IPAM产生
> 
> 一些建议 （1）cni 是什么选项，是否工作正常，使得 pod 流量能够出 宿主机，与 同子网 其它ip 通信，例如可以先测试 pod 到 自己子网网关的连通性，是否 路由器 、sriov、vlan 规划问题 （2）给出的描述中，是2个跨子网的网段，2个网段的 路由器 是否 子网打通 （3）画出 拓扑图，逐跳 确认 ( pod 178.18.41.0/24) to ( 178.18.41.0/24 网关 ) to (178.18.42.0/24 网关) to ( pod 178.18.42.0/24) 的连通性

好的  另外咨询个问题   spiderpool 支持Pod固定IP吗    我看文档里介绍是支持Pod Affinity 。 那样的话每个Pod创建一个对应的ippool ，ippool里只指定一个IP  用这种方式能实现Pod固定IP吗

**Comment by weizhoublue** [comment]
支持，且功能非常强大，马上 发版 0.4.0 会 进一步 完善文档

手动 创建 池，分配 应用亲和性，直接完成。（ 马上 发版 0.4.0 能够为 无状态 应用 自动创建 固定池，且 弹性扩缩 ip 数量 ）

能为 有状态 应用 直接 固定到 pod ip

**Comment by pengbinbin1** [comment]
> 支持，且功能非常强大，马上 发版 0.4.0 会 进一步 完善文档
> 
> 对于无状态应用，可手动 创建 池，分配 应用亲和性，直接完成 https://github.com/spidernet-io/spiderpool/tree/main/docs/example/ippool-affinity-pod。（ 马上 发版 0.4.0 能够为 无状态 应用 自动创建 固定池，且 弹性扩缩 ip 数量 ，固定 ip 管理 0 成本）
> 
> 无论是否 使用 独享一个池，都能为 有状态 应用 直接 固定到 pod ip

与其说是固定IP  其实是通过Pod Affinity 固定IP pool  可以这样理解吗

**Comment by weizhoublue** [comment]
该概念 是由 应用决定的

无状态应用，pod name uuid 都会 随着重启 变化，没法 固定ip 和 pod 的绑定关系，只能说 deployment 固定 ip 范围，所以，可以理解为 “通过Pod Affinity 固定IP pool”

有状态应用，pod name 是固定的，所以 无论是否 有 Pod Affinity， spiderpool 都能 固定到 pod 和 ip  唯一关系

**Comment by pengbinbin1** [comment]
> 固定IP 概念 是 相对 不同应用 有不同的定义
> 
> 无状态应用，pod name uuid 都会 随着重启 变化，例如一个deployment 下 5个pod，同时都重启，没法 固定ip 和 pod 的 唯一 映射关系，只能说 deployment 固定 ip 范围，所以，可以理解为 “通过Pod Affinity 固定IP pool”
> 
> 有状态应用，pod name 是固定的，所以 无论是否 有 Pod Affinity， spiderpool 都能 固定到 pod 和 ip 唯一关系

了解了  谢谢

**Comment by pengbinbin1** [comment]
> 固定IP 概念 是 相对 不同应用 有不同的定义
> 
> 无状态应用，pod name uuid 都会 随着重启 变化，例如一个deployment 下 5个pod，同时都重启，没法 固定ip 和 pod 的 唯一 映射关系，只能说 deployment 固定 ip 范围，所以，可以理解为 “通过Pod Affinity 固定IP pool”
> 
> 有状态应用，pod name 是固定的，所以 无论是否 有 Pod Affinity， spiderpool 都能 固定到 pod 和 ip 唯一关系

还有一个问题  如果使用Multus CNI的话 ,  定义的NetworkAttachementDefinition  和 IPPool 之间是没有关系的？ 目前无法指定哪个 NAD 使用哪个 IPPool吧？

**Comment by Icarus9913** [comment]
> > 固定IP 概念 是 相对 不同应用 有不同的定义
> > 无状态应用，pod name uuid 都会 随着重启 变化，例如一个deployment 下 5个pod，同时都重启，没法 固定ip 和 pod 的 唯一 映射关系，只能说 deployment 固定 ip 范围，所以，可以理解为 “通过Pod Affinity 固定IP pool”
> > 有状态应用，pod name 是固定的，所以 无论是否 有 Pod Affinity， spiderpool 都能 固定到 pod 和 ip 唯一关系
> 
> 还有一个问题 如果使用Multus CNI的话 , 定义的NetworkAttachementDefinition 和 IPPool 之间是没有关系的？ 目前无法指定哪个 NAD 使用哪个 IPPool吧？

支持的，对于自己手动创建的池，想使用多网卡功能，可以参照一下
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/ippool-multi.md
这里面的yaml例子。

对于使用了SpiderSubnet功能，我们后台可以为应用自动创建一个池，也是支持多网卡功能的，可以参照一下
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/spider-subnet.md


后续我们还会继续加强文档的优化 :)

**Comment by iiiceoo** [comment]
一般推荐这样使用（这个部分的文档目前是缺失的），使用了该 net-attach-def 的 Pod 则会从 pool1 中分配 IPv4 IP，多填就是[备选池](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/ippool-multi.md)：

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
  namespace: kube-system
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "macvlan",
        "plugins": [
            {
                "type": "macvlan",
                "master": "eth0",
                "mode": "bridge",
                "ipam": {
                    "type": "spiderpool",
                    "default_ipv4_ippool": ["pool1"],
                    "default_ipv6_ippool": ["pool2"]
                }
            }
        ]
    }
```

也可以使用 `ipam.spidernet.io/ippools` 注解，它的优先级高于 CNI 配置文件中的 `default_ipv4_ippool` 字段，不过会麻烦一些，可以参考[这里](https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/multi-interfaces-annotation.md)。
