### ISSUE TITLE
website format issue

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#1586]
some format error

<img width="761" alt="企业微信截图_d60c6055-45ea-463f-b98e-1e0b030cb34a" src="https://user-images.githubusercontent.com/45163302/228537175-f600c501-8f34-4844-a56f-b848805ccd67.png">

**Comment by weizhoublue** [comment]
@windsonsea  there is lots of similar issue on other pages, so reopen this

**Comment by bertreyking** [comment]
- updating the mkdoc.yml configuration file should fix the code formatting issues
```
markdown_extensions:
  - meta
  - toc
  - tables
  - fenced_code
  - tables
  - attr_list
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
```
