### ISSUE TITLE
docs: In the cross-subnet example of ippool-affinity-node.md, the gateway is not set in the created ippool, which will cause connectivity problems.

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#1793]
Reference documents: https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/ippool-affinity-node.md

ippool settings：
```
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: master-ipv4-ippool
spec:
  subnet: 172.18.41.0/24
  ips:
  - 172.18.41.40
  nodeAffinity:
    matchExpressions:
    - {key: node-role.kubernetes.io/master, operator: Exists}
```

If the IPPool is created according to the yaml in the example, the pod is assigned an IP, but there will be a lack of default routes within the pod, making it impossible to achieve cross-subnet communication.
