### ISSUE TITLE
wrong ifacer and coordinator for SpiderMultusConfig

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2006]
```
cat <<EOF | kubectl apply -f -
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: test
  namespace: default
spec:
  cniType: macvlan
  macvlan:
    master: ["eth0"]
    vlanID: 100
EOF

```

its multus result is following

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test
  namespace: default
spec:
  config: -|
	{
	  "cniVersion": "0.3.1",
	  "name": "test",
	  "plugins": [
	    {
	      "type": "ifacer",
	      "ipam": {},
	      "dns": {},
	      "interfaces": [
	        "eth0"
	      ],
	      "vlanID": 100
	    },
	    {
	      "type": "macvlan",
	      "ipam": {
	        "type": "spiderpool"
	      },
	      "master": "eth0.100",
	      "mode": "bridge"
	    },
	    {
	      "type": "coordinator"
	    }
	  ]
	}
```

it should be no ipam and dns for coordinator and ifacer
