### ISSUE TITLE
sriov doc

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2132]
https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install/underlay/get-started-sriov-zh_CN.md

(1)
如果组件未就绪, 可能需要给 sriov 工作节点打上 label: 'node-role.kubernetes.io/worker=""'

--------  根据代码，一定要 打上 该 lebel，才会在该节点上安装 组件 和 上报 sriov 状态 ， 而不是 “可能”

```
              lo := &client.MatchingLabels{
                "node-role.kubernetes.io/worker": "",
                "kubernetes.io/os":               "linux",
              }
```

(2)
pod yaml 中， resource 写错 

spidernet/sriov_netdevice: '1' 

------ spidernet.io/sriov_netdevice: '1' 

(3)
创建 SpiderMultusConfig 实例 步骤中，需要给小白说明下  如下是怎么拼出来的

```
spec:
  sriov:
    resourceName: spidernet.io/sriov_netdevice
```

(4)
安装 SriovNetworkNodePolicy 步骤，提示： 可能会导致主机重启

(5)

```
kind: SriovNetworkNodePolicy
metadata:
  name: policy
  namespace: kube-system
spec:
  nodeSelector:
    kubernetes.io/os: "linux"
  # 这个名字不能带特殊字符， resource name "mellanox-vfio" contains invalid characters
  resourceName: mellanox
```

(6)
只有状态 同步完成  Succeeded ，才能继续
```
~# kubectl get SriovNetworkNodeState -A
NAMESPACE     NAME         SYNC STATUS   AGE
kube-system   10-20-1-10   Succeeded     101m
kube-system   10-20-1-20   InProgress    106m
```
