### ISSUE TITLE
json format in SpiderMultusConfig 

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2151]
it did not check the json format

succeed to create 
```
cat <<EOF | kubectl apply -f -
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: ovs-tet
  namespace: kube-system
spec:
  cniType: custom
  customCNI: '{ abc }'
EOF


```
