### ISSUE TITLE
feature: verify working with istio

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/spiderpool#2201]
kinds of communication manner,

**Comment by ty-dc** [comment]
I don’t quite understand this function, can you elaborate? Or what do we need to do? Do you two have any understanding or suggestions? @Icarus9913 @cyclinder

**Comment by ty-dc** [comment]
## istio and spiderpool verification

### Create a namespace and label it with sidecar injection

```bash
[root@controller-node-1 ~]# kubectl get ns spider-istio -oyaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-11-28T07:25:18Z"
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: spider-istio
  name: spider-istio
  resourceVersion: "515568"
  uid: 054caacb-ef62-4b6d-a6e5-57733bac3222
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

### Create an application and use spiderpool to assign IPs

- Specify network configuration and ip pool via annotations `ipam.spidernet.io/ippool` and `v1.multus-cni.io/default-network` allocation.
- 

```
cat <<EOF | kubectl create -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spider-istio-test
  name: spider-istio-test
  namespace: spider-istio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spider-istio-test
  template:
    metadata:
      labels:
        app: spider-istio-test
      annotations:
        ipam.spidernet.io/ippool: |-
          {
            "ipv4": ["ipv4-ippool"]
          }
        v1.multus-cni.io/default-network: kube-system/macvlan
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: spider-istio-test
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spider-istio-test
  namespace: spider-istio
spec:
  ports:
  - name: http-9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: spider-istio-test
  type: ClusterIP
EOF
```

Verify creation is successful.

```
[root@controller-node-1 ~]# kubectl get po -owide
NAME                               READY   STATUS    RESTARTS   AGE     IP             NODE            NOMINATED NODE   READINESS GATES
spider-istio-test-d9c9d66f-d9fbk   2/2     Running   0          5m25s   10.6.168.225   worker-node-1   <none>           <none>
```

Verify cluster east-west access

```
[root@controller-node-1 ~]# curl 10.6.168.225:9090
Hello World!

[root@controller-node-1 ~]# kubectl get svc -n spider-istio
NAME                    TYPE         CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
spider-istio-test   ClusterIP   10.233.8.146   <none>             9090/TCP   3h16m

[root@controller-node-1 ~]# curl 10.233.8.146:9090
Hello World!
```

Create istio mesh gateway, gateway rules, virtual services.

```
kubectl get po -n spider-istio
NAME                                                  READY   STATUS    RESTARTS   AGE
spider-istio-gw-b6778cd9c-nvpfr   1/1          Running   0          29m

[root@controller-node-1 ~]# kubectl get gateways.networking.istio.io -n spider-istio
NAME                   AGE
spider-istio-gw-rule   3h32m

[root@controller-node-1 ~]# kubectl get virtualservices.networking.istio.io  -n spider-istio
NAME              GATEWAYS                                HOSTS              AGE
spider-istio-vs   ["spider-istio/spider-istio-gw-rule"]   ["www.cali.com"]   3h30m
```

Access outside the cluster

```
root@test ~ # curl 10.6.168.232 -H "host:www.cali.com"
Hello World!
```
