### ISSUE TITLE
Is it more appropriate to use pfNames in documentation?

### ISSUE THREAD

**Issue by ty-dc** [spidernet-io/spiderpool#2583]
### The Type of Document Issue

Outdated

### What's wrong with this document?

Change the following
```
      nicSelector:
        deviceID: "1017"
        rootDevices:
          - 0000:04:00.0
        vendor: "15b3"
```
content to
```
      nicSelector:
        pfNames:
          - enp4s0f0np0
```

### Document Path Or Link

https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install/underlay/get-started-sriov-zh_CN.md
