### ISSUE TITLE
bug: the SpiderMultusConfig of macvlan mode can not be applied

### ISSUE THREAD

**Issue by hansedong** [spidernet-io/spiderpool#2700]
### Spiderpool Version

v0.8.1

### Bug Type

Installation Issue

### Main CNI

macvlan

### What happened?

```yaml
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: macvlan-conf
  namespace: kube-system
spec:
  cniType: macvlan
  macvlan:
    master:
    - bond0
```

```shell
kubectl apply -f spiderpool.cni.yaml
```

```
Warning: resource spidermultusconfigs/macvlan-conf is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The SpiderMultusConfig "macvlan-conf" is invalid: spec.cniType: Forbidden: the cniType macvlan only supports spec.macvlanConfig, please remove other CNI configs
```

### What did you expect to happen?

other resources as bellow:

```shell
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: ippool-default
spec:
  ips:
  - "10.131.120.1-10.131.127.255"
  subnet: 10.131.0.0/16
  default: true
  disable: false
  gateway: 10.131.64.1
  multusName:
  - macvlan-conf
```

I followed the document and wrote a simple configuration, but I couldn't create it successfully. May I ask where the possible reasons are?

### How to reproduce it (as minimally and precisely as possible)

1. helm install spiderpool v0.8.1(the lastest version)
2. apply the yaml

### Additional Context

no
