### ISSUE TITLE
DRA: support for claim resources with resourcecliam

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/spiderpool#3334]
### What would you like to be added?

support for claim resources with resourcecliam:

```
apiVersion: network.resource.spidernet.io/v1alpha1
kind: SpiderClaimParameters
metadata:
  name: demo
spec:
  resources:
    spidernet.io/shared_rdma_netdevice: 1
    spidernet.io/sriov_rdma_netdevices 1
---
apiVersion: resource.k8s.io/v1alpha1
kind: ResourceClaimTemplate
metadata:
  name: demo-template
spec:
  spec:
    resourceClassName: network.spidernet.io           
    parametersRef:
      apiGroup: network.resource.spidernet.io/v1alpha1
      kind: spiderClaimParameters
      name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: demo
    image: ubuntu:2204
    resources:
      limits:
        spidernet.io/shared_rdma_netdevice: 1      
      cliams:
      - demo-rc
  resourceClaims:
  - name: demo-rc
    source:
      resourceClaimTemplate: demo-template
```
