### ISSUE TITLE
SR-IOV VF inside the pod sometimes encounters the issue of "No IB devices found" When pods run in non-privileged mode

### ISSUE THREAD

**Issue by zhangjiongwx** [spidernet-io/spiderpool#4345]
### Spiderpool Version

v1.0.0-rc1

### Kubernetes Version
v1.31.0

### Main CNI

sriov

### bug description

When I use a Deployment to deploy two SR-IOV replicas with IPC_LOCK capability to a node, sometimes both replicas work normally, sometimes one works normally and one fails, sometimes both fail.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netperf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netperf
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: spiderpool/mlx-sriov
      labels:
        app: netperf
    spec:
      nodeName: kube-worker-2
      containers:
        - name: netperf
          image: netperf:1.3
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              spidernet.io/mlx_vfs: 1
          securityContext:
            privileged: false
            capabilities:
              add: ["IPC_LOCK"]
```
When entering the problematic pod and executing the ibv_devinfo command, it shows the error "No IB devices found".
```shell
# ibv_devinfo
No IB devices found
```
However , it can print information normally when executing RDMA-related commands
```shell
# rdma link
link mlx5_7/1 state ACTIVE physical_state LINK_UP netdev net1
# rdma dev
13: mlx5_7: node_type ca fw 16.35.4030 node_guid 6200:a5ff:fe9d:3b24 sys_image_guid 6cb3:1103:0076:e1a4
# ip a show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
24: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4500 qdisc mq state UP group default qlen 1000
    link/ether 62:00:a5:9d:3b:24 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.4/16 brd 192.168.255.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::6000:a5ff:fe9d:3b24/64 scope link
       valid_lft forever preferred_lft forever
359: eth0@if360: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 7a:6e:8f:1d:e8:50 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.244.2.106/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::786e:8fff:fe1d:e850/64 scope link
       valid_lft forever preferred_lft forever
```
**When I enabled privileged mode in the deployment, this issue no longer occurred, and everything ran normally.**

**Comment by cyclinder** [comment]
Hi @zhangjiongwx, thanks for the report, Could you show the spidermultusconfig `spiderpool/mlx-sriov` and run the command: `kubectl get nodes -o json | jq -r  '.items[] | {nodeName: .metadata.name, allocatable: .status.allocatable}'` ?

**Comment by zhangjiongwx** [comment]
@cyclinder This is my ippool and multusconfig
```yaml
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
    name: worker-2-ippool
spec:
    gateway: 192.168.0.1
    ips:
        - 192.168.1.2-192.168.1.254
    subnet: 192.168.0.0/16
    nodeName:
        - kube-worker-2
---
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
    name: worker-1-ippool
spec:
    gateway: 192.168.0.1
    ips:
        - 192.168.2.2-192.168.2.254
    subnet: 192.168.0.0/16
    nodeName:
        - kube-worker-1
---
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
    name: mlx-sriov
    namespace: spiderpool
spec:
    cniType: sriov
    sriov:
        resourceName: spidernet.io/mlx_vfs
        enableRdma: true
        ippools:
            ipv4: ["worker-1-ippool", "worker-2-ippool"]
```
and the command output
```shell
# kubectl get nodes -o json | jq -r  '.items[] | {nodeName: .metadata.name, allocatable: .status.allocatable}'
{
  "nodeName": "kube-control-plane",
  "allocatable": {
    "cpu": "12",
    "ephemeral-storage": "241473945201",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "15679072Ki",
    "pods": "110",
    "spidernet.io/mlx_100ge_vfs": "0",
    "spidernet.io/mlx_vfs": "0"
  }
}
{
  "nodeName": "kube-worker-1",
  "allocatable": {
    "cpu": "20",
    "ephemeral-storage": "241473945201",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "32217356Ki",
    "pods": "110",
    "spidernet.io/mlx_vfs": "6"
  }
}
{
  "nodeName": "kube-worker-2",
  "allocatable": {
    "cpu": "16",
    "ephemeral-storage": "241473945201",
    "hugepages-1Gi": "0",
    "hugepages-2Mi": "0",
    "memory": "98216932Ki",
    "nvidia.com/gpu": "10",
    "pods": "110",
    "spidernet.io/mlx_vfs": "6"
  }
}
```

**Comment by cyclinder** [comment]
Please also provide the info:

- kubectl get network-attachment-definitions.k8s.cni.cncf.io -n spiderpool mlx-sriov -o yaml
- rdma system

**Comment by zhangjiongwx** [comment]
@cyclinder 
```shell
# kubectl get network-attachment-definitions.k8s.cni.cncf.io -n spiderpool mlx-sriov -o yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: spidernet.io/mlx_vfs
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"spiderpool.spidernet.io/v2beta1","kind":"SpiderMultusConfig","metadata":{"annotations":{},"name":"mlx-sriov","namespace":"spiderpool"},"spec":{"cniType":"sriov","sriov":{"enableRdma":true,"ippools":{"ipv4":["worker-1-ippool","worker-2-ippool"]},"resourceName":"spidernet.io/mlx_vfs"}}}
  creationTimestamp: "2024-10-29T01:25:51Z"
  generation: 1
  name: mlx-sriov
  namespace: spiderpool
  ownerReferences:
  - apiVersion: spiderpool.spidernet.io/v2beta1
    blockOwnerDeletion: true
    controller: true
    kind: SpiderMultusConfig
    name: mlx-sriov
    uid: 847c0e82-3582-4d73-a959-201a0d300c06
  resourceVersion: "10236155"
  uid: 93eba61b-2912-43e2-9486-c3c9b019aedd
spec:
  config: '{"cniVersion":"0.3.1","name":"mlx-sriov","plugins":[{"vlan":0,"minTxRate":0,"maxTxRate":0,"type":"sriov","ipam":{"type":"spiderpool","default_ipv4_ippool":["worker-1-ippool","worker-2-ippool"]}},{"type":"rdma"},{"txQueueLen":0,"detectIPConflict":false,"detectGateway":false,"tunePodRoutes":true,"mode":"auto","type":"coordinator"}]}'
# rdma system
netns exclusive copy-on-fork on
```
In the problematic pod
```shell
# rdma system
netns exclusive copy-on-fork on
# ls /dev/infiniband
issm7  rdma_cm  umad7  uverbs7
```

**Comment by cyclinder** [comment]
It seems all your configs are correct. can you also show the sriovnetworknodepolicy?

**Comment by zhangjiongwx** [comment]
@cyclinder This issue occurs quite frequently，but when I switched to privileged mode，everything works well. 
```yaml
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
    name: mlx-sriov
    namespace: spiderpool
spec:
    nodeSelector:
        feature.node.kubernetes.io/network-sriov.capable: "true"
    resourceName: mlx_vfs
    priority: 99
    mtu: 4500
    numVfs: 6
    nicSelector:
        pfNames: ["enp1s0f0np0"]
    deviceType: netdevice
    isRdma: true
```
