### ISSUE TITLE
Multi values for the RDMA resource injection annotation of the spidermultusconfig 

### ISSUE THREAD

**Issue by cyclinder** [spidernet-io/spiderpool#4358]
### What would you like to be added?

Add support for `cni.spidernet.io/rdma-resource-inject` multiple values, which are separated by commas. This can be used for different purposes with the same spidermultusconfig representation.

目前 `cni.spidernet.io/rdma-resource-inject` 这个 annotation 用于表示创建 AI 应用时自动注入 RDMA 网络资源，参考文档：https://github.com/spidernet-io/spiderpool/blob/main/docs/usage/install/ai/get-started-macvlan-zh_CN.md#%E5%9F%BA%E4%BA%8E-webhook-%E8%87%AA%E5%8A%A8%E6%B3%A8%E5%85%A5-rdma-%E7%BD%91%E7%BB%9C%E8%B5%84%E6%BA%90。目前该注解打在 spidermultusconfig 上 时只有一个 value，只能表示同一组的 spidermultusconfig 配置。客户可能有特殊需求，比如不同的 AI 应用可能希望 4 网卡或 8 网卡，所以需要给同一个 spidermutlsuconfig 赋予多个意义。

希望能够支持该注解的多 value, 类似： `cni.spidernet.io/rdma-resource-inject:  nic4,nic8`

```
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderMultusConfig
metadata:
  name: gpu1-sriov
  namespace: spiderpool
  annotations:
    cni.spidernet.io/rdma-resource-inject: nic4,nic8
spec:
  cniType: macvlan
  macvlan:
    master: ["enp11s0f0np0"]
    enableRdma: true
    rdmaResourceName: spidernet.io/gpu1rdma
  ippools:
    ipv4: ["gpu1-net11"]
```

4 网卡 AI pod1:

```
spec:
  template:
    metadata:
      annotations:
        cni.spidernet.io/rdma-resource-inject: nic4
```

8 网卡 AI pod2:

```
spec:
  template:
    metadata:
      annotations:
        cni.spidernet.io/rdma-resource-inject: nic8
```
