### ISSUE TITLE
Installation Instructions for EKS / Default Install Method Fails on EKS

### ISSUE THREAD

**Issue by infinitydon** [spidernet-io/spiderpool#4954]
Hi SpiderPool team,

**_Please consider:_**

- Documenting the installation procedure for EKS — including any Helm values, CRDs, or Kubernetes settings that need to be customized.

- Providing an EKS-specific example or guide to help users get started quickly.

- Clarifying any known compatibility issues or limitations with Amazon EKS.

I tried sometimes ago and I noticed the default installation fails, I think this has to be with detecting the PODcidr or ServiceCIDR

Thanks

**Comment by infinitydon** [comment]
@cyclinder 

From the test I carried out now, I used the following install command:

```
helm install spiderpool spiderpool/spiderpool --namespace kube-system --set multus.multusCNI.install=false --set coordinator.enabled=false
```

I only need the IPAM feature of spiderPool but the Init Container keeps complaining about controller not been ready:

```
kubectl -n kube-system get po | grep spider
spiderpool-agent-8ktl7                   1/1     Running   0               3m33s
spiderpool-agent-s444c                   1/1     Running   0               3m33s
spiderpool-controller-6b99fbfffd-8x6mq   1/1     Running   0               3m33s
spiderpool-init-xztcq                    1/1     Running   0               3m33s
```

```
 kubectl -n kube-system logs spiderpool-init-xztcq | more
{"level":"INFO","ts":"2025-06-25T13:26:20.509Z","logger":"Spiderpool-Init","caller":"cmd/config.go:159","msg":"Ignore creating default Coordinator"}
{"level":"INFO","ts":"2025-06-25T13:26:20.509Z","logger":"Spiderpool-Init","caller":"cmd/config.go:198","msg":"Ignore creating default IPv4 Subnet or IPPool"}
{"level":"INFO","ts":"2025-06-25T13:26:20.509Z","logger":"Spiderpool-Init","caller":"cmd/config.go:237","msg":"Ignore creating default IPv6 Subnet or IPPool"}
{"level":"INFO","ts":"2025-06-25T13:26:20.509Z","logger":"Spiderpool-Init","caller":"cmd/config.go:282","msg":"Init default config: {Namespace:kube-system ControllerName:spiderpool-controller AgentName:spiderpool-agent CoordinatorName: CoordinatorMode: CoordinatorPodCIDRType: CoordinatorPodDefaultRouteNic: Coord
inatorPodMACPrefix: CoordinatorVethLinkAddress: CoordinatorTunePodRoutes:false CoordinatorHijackCIDR:[] V4SubnetName: V4IPPoolName: V4CIDR: V4IPRanges:[] V4Gateway: V6SubnetName: V6IPPoolName: V6CIDR: V6IPRanges:[] V6Gateway: enableMultusConfig:true DefaultCNIDir:/etc/cni/net.d DefaultCNIName: DefaultCNINamespac
e:kube-system MultusConfigMap: ReadinessFile:/etc/spiderpool/ready}"}
{"level":"INFO","ts":"2025-06-25T13:26:20.523Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:22.525Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:24.528Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:26.531Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:28.533Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:30.539Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:32.541Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:34.543Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:36.579Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:38.582Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:40.586Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:42.588Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
{"level":"INFO","ts":"2025-06-25T13:26:44.591Z","caller":"cmd/client.go:125","msg":"Spiderpool controller is not ready, recheck in 2s"}
```

What could be wrong?

**Comment by cyclinder** [comment]
> I only need the IPAM feature of spiderPool, but the spiderpool-init job keeps complaining about the controller not being ready:

This should be a bug, your controller pod was ready. I saw your helm installation command; you don't use the coordinator. We highly recommend enabling this feature, as this may be why the spiderpool-init job keeps complaining. Can you introduce your usage to me? What CNI are you using?

**Comment by cyclinder** [comment]
Thanks for your information.

If you see the spiderpool-init job giving errors: `Spiderpool controller is not ready, recheck in 2s`. This just checks the spiderpool-controller endpoint has more than one subnet. please provide the spiderpool endpoint information by using command:

```
kubectl get ep -n kube-system spiderpool-controller -o yaml
```


If you see the spiderpool-init job giving errors: `{"level":"INFO","ts":"2025-06-26T12:28:49.158Z","caller":"cmd/client.go:64","msg":"Failed to create default Coordinator default, recreate in 2s: Internal error occurred: failed calling webhook \"spidercoordinator.spiderpool.spidernet.io\": failed to call webhook: Post \"https://spiderpool-controller.kube-system.
svc:5722/mutate-spiderpool-spidernet-io-v2beta1-spidercoordinator?timeout=10s\": context deadline exceeded"}`

Please check the CRD has exist:

```
kubectl get crd spidercoordinators.spiderpool.spidernet.io
```

**Comment by infinitydon** [comment]
See the output of the commands you provided.

**kubectl get ep -n kube-system spiderpool-controller -o yaml**:

```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-26T12:27:38Z"
  creationTimestamp: "2025-06-26T12:27:17Z"
  labels:
    app.kubernetes.io/component: spiderpool-controller
    app.kubernetes.io/instance: spiderpool
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spiderpool
    app.kubernetes.io/version: 1.0.3
    helm.sh/chart: spiderpool-1.0.3
  name: spiderpool-controller
  namespace: kube-system
  resourceVersion: "14089960"
  uid: 3a000bb9-e737-401b-8b98-bd3938d7a13e
subsets:
- addresses:
  - ip: 10.10.1.154
    nodeName: ip-10-10-1-154.ec2.internal
    targetRef:
      kind: Pod
      name: spiderpool-controller-5bf5cb6457-rg9kf
      namespace: kube-system
      uid: a42c3ac6-6ac1-4fba-8499-6ec0f51e7a02
  ports:
  - name: http
    port: 5720
    protocol: TCP
  - name: webhook
    port: 5722
    protocol: TCP
```

**kubectl get crd spidercoordinators.spiderpool.spidernet.io**:

```
NAME                                         CREATED AT
spidercoordinators.spiderpool.spidernet.io   2025-06-26T12:27:13Z
```

**Comment by cyclinder** [comment]
Thanks for your information. It looks like everything is fine. 

```
Failed to create default Coordinator default, recreate in 2s: Internal error occurred: failed calling webhook \"spidercoordinator.spiderpool.spidernet.io\": failed to call webhook: Post \"https://spiderpool-controller.kube-system.
svc:5722/mutate-spiderpool-spidernet-io-v2beta1-spidercoordinator?timeout=10s\": context deadline exceeded"}
```

The error indicates that there seems to be a communication issue between the controller pod and the API server.

**Comment by cyclinder** [comment]
It's so strange. We have never met this issue before. Have you met this issue every time or sometimes?

**Comment by cyclinder** [comment]
Are you sure that spiderpool-init and controller pods are both host network?

**Comment by infinitydon** [comment]
Both have the HostNetwork.

**spiderpool-init:**

```
kubectl -n kube-system get po spiderpool-init-6pbb7 -o yaml | kubectl neat
apiVersion: v1
kind: Pod
metadata:
  labels:
    batch.kubernetes.io/controller-uid: fe9717d1-3a55-4994-8eb4-ec7c63a0e27f
    batch.kubernetes.io/job-name: spiderpool-init
    controller-uid: fe9717d1-3a55-4994-8eb4-ec7c63a0e27f
    job-name: spiderpool-init
  name: spiderpool-init-6pbb7
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/bin/spiderpool-init
    env:
    - name: SPIDERPOOL_NAMESPACE
      value: kube-system
    - name: SPIDERPOOL_CONTROLLER_NAME
      value: spiderpool-controller
    - name: SPIDERPOOL_AGENT_NAME
      value: spiderpool-agent
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_NAME
      value: default
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_MODE
      value: auto
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_POD_CIDR_TYPE
      value: auto
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_DETECT_GATEWAY
      value: "false"
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_DETECT_IP_CONFLICT
      value: "false"
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_TUNE_POD_ROUTES
      value: "true"
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_HIJACK_CIDR
      value: '["169.254.0.0/16"]'
    - name: SPIDERPOOL_INIT_DEFAULT_COORDINATOR_VETH_LINK_ADDRESS
    - name: SPIDERPOOL_INIT_ENABLE_MULTUS_CONFIG
      value: "true"
    - name: SPIDERPOOL_INIT_DEFAULT_CNI_NAME
    - name: SPIDERPOOL_INIT_DEFAULT_CNI_NAMESPACE
      value: kube-system
    - name: SPIDERPOOL_INIT_DEFAULT_CNI_DIR
      value: /etc/cni/net.d
    image: ghcr.io/spidernet-io/spiderpool/spiderpool-controller:v1.0.3
    name: spiderpool-init
    volumeMounts:
    - mountPath: /etc/cni/net.d
      name: cni
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-drwrp
      readOnly: true
  hostNetwork: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  serviceAccountName: spiderpool-init
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /etc/cni/net.d
    name: cni
  - name: kube-api-access-drwrp
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
```

**spiderpool-controller:**

```
kubectl -n kube-system get po spiderpool-controller-5bf5cb6457-rg9kf -o yaml | kubectl neat
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: spiderpool-controller
    app.kubernetes.io/instance: spiderpool
    app.kubernetes.io/name: spiderpool
    pod-template-hash: 5bf5cb6457
  name: spiderpool-controller-5bf5cb6457-rg9kf
  namespace: kube-system
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: spiderpool-controller
              app.kubernetes.io/instance: spiderpool
              app.kubernetes.io/name: spiderpool
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - args:
    - daemon
    - --config-path=/tmp/spiderpool/config-map/conf.yml
    - --tls-server-cert=/etc/tls/tls.crt
    - --tls-server-key=/etc/tls/tls.key
    command:
    - /usr/bin/spiderpool-controller
    env:
    - name: SPIDERPOOL_LOG_LEVEL
      value: info
    - name: SPIDERPOOL_ENABLED_METRIC
      value: "false"
    - name: SPIDERPOOL_ENABLED_DEBUG_METRIC
      value: "false"
    - name: SPIDERPOOL_METRIC_HTTP_PORT
      value: "5721"
    - name: SPIDERPOOL_GOPS_LISTEN_PORT
      value: "5724"
    - name: SPIDERPOOL_WEBHOOK_PORT
      value: "5722"
    - name: SPIDERPOOL_HEALTH_PORT
      value: "5720"
    - name: SPIDERPOOL_GC_IP_ENABLED
      value: "true"
    - name: SPIDERPOOL_GC_STATELESS_TERMINATING_POD_ON_READY_NODE_ENABLED
      value: "true"
    - name: SPIDERPOOL_GC_STATELESS_TERMINATING_POD_ON_NOT_READY_NODE_ENABLED
      value: "true"
    - name: SPIDERPOOL_GC_ENABLE_STATELESS_RUNNING_POD_ON_EMPTY_POD_STATUS_IPS
      value: "false"
    - name: SPIDERPOOL_GC_ADDITIONAL_GRACE_DELAY
      value: "0"
    - name: SPIDERPOOL_GC_DEFAULT_INTERVAL_DURATION
      value: "600"
    - name: SPIDERPOOL_MULTUS_CONFIG_ENABLED
      value: "true"
    - name: SPIDERPOOL_CNI_CONFIG_DIR
      value: /etc/cni/net.d
    - name: SPIDERPOOL_COORDINATOR_ENABLED
      value: "true"
    - name: SPIDERPOOL_COORDINATOR_DEAFULT_NAME
      value: default
    - name: SPIDERPOOL_CILIUM_CONFIGMAP_NAMESPACE_NAME
      value: kube-system/cilium-config
    - name: SPIDERPOOL_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: SPIDERPOOL_POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: SPIDERPOOL_CONTROLLER_DEPLOYMENT_NAME
      value: spiderpool-controller
    image: ghcr.io/spidernet-io/spiderpool/spiderpool-controller:v1.0.3
    lifecycle:
      preStop:
        exec:
          command:
          - /usr/bin/spiderpool-controller
          - shutdown
    livenessProbe:
      failureThreshold: 6
      httpGet:
        host: 127.0.0.1
        path: /v1/runtime/liveness
        port: 5720
      initialDelaySeconds: 10
    name: spiderpool-controller
    ports:
    - containerPort: 5720
      name: http
    - containerPort: 5722
      name: webhook
    readinessProbe:
      httpGet:
        host: 127.0.0.1
        path: /v1/runtime/readiness
        port: 5720
      initialDelaySeconds: 15
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    startupProbe:
      failureThreshold: 30
      httpGet:
        host: 127.0.0.1
        path: /v1/runtime/startup
        port: 5720
      periodSeconds: 2
    volumeMounts:
    - mountPath: /tmp/spiderpool/config-map
      name: config-path
      readOnly: true
    - mountPath: /etc/cni/net.d
      name: cni-conf-dir
      readOnly: true
    - mountPath: /etc/tls
      name: tls
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-dfvsw
      readOnly: true
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  serviceAccountName: spiderpool-controller
  tolerations:
  - operator: Exists
  volumes:
  - configMap:
      name: spiderpool-conf
    name: config-path
  - hostPath:
      path: /etc/cni/net.d
      type: DirectoryOrCreate
    name: cni-conf-dir
  - name: tls
    projected:
      defaultMode: 256
      sources:
      - secret:
          items:
          - key: tls.crt
            path: tls.crt
          - key: tls.key
            path: tls.key
          name: spiderpool-controller-server-certs
  - name: kube-api-access-dfvsw
    projected:
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.namespace
            path: namespace
```

Do you have an idea of where I should look again or someone else that can assist?
